### ISSUE TITLE
Build fails, Linux

### ISSUE THREAD

**Issue by marcoose777** [paynebc/tunefish#10]
Hi, the current Master branch cannot be built on linux. The erroneous code is in line 298 of Source/runtime/runtime.hpp, and concerns an unspecified type 'eSize', this type is not declared anywhere in the codebase. Make/g++ suggest changing it to eSign which makes no sense.

Errant function:
`template<class MEMBER, class PARENT>
PARENT & eGetContainerOf(MEMBER &memberInst, const MEMBER PARENT::*memberVar)
{
    const eSize off = reinterpret_cast<eSize>(&(reinterpret_cast<PARENT *>(0)->*memberVar));
    return *reinterpret_cast<PARENT *>(reinterpret_cast<eSize>(memberInst)-off);
}
`
Greping for 'eGetContainerOf' shows only the function definition inside of the runtime.hpp file, unused.

As an aside I've never seen Yorkshire code before, fluent in eeee bye gum.

**Comment by opless** [comment]
Hi, not a developer ... but can you comment with the version of gcc that you’re using and the distribution and version of Linux that you find this problem with?

It’s likely to be relevant.

**Comment by paynebc** [comment]
sorry, that method is indeed not used, so I removed it. that should fix compilation hopefully

**Comment by marcoose777** [comment]
Thanks paynebc, I'll try again

**Comment by marcoose777** [comment]
I can confirm the build now works, however there is a memory access violation that I've attached to kmattheusen's bug post. I think they're related
