### ISSUE TITLE
Update to/Add VST3?

### ISSUE THREAD

**Issue by simonvanderveldt** [paynebc/tunefish#11]
Thanks for the nice synth!

Small question: Can VST3 be added (or maybe just straight up replace VST2)? https://github.com/steinbergmedia/vst3sdk
AFAIK there's a VST3 option available within JUCE.

The VST3 SDK is a lot easier to work with license wise than the VST2 one, so switching to VST3 will make it a lot easier to get tunefish packaged for Linux distro's.

**Comment by paynebc** [comment]
VST3 should already be part of the build

**Comment by simonvanderveldt** [comment]
> VST3 should already be part of the build

@paynebc According to the Makefile (for Linux) it's disabled, see https://github.com/paynebc/tunefish/blob/de0ad042eb1077f1e2f52a05455841b9e9d3d677/src/tunefish4/Builds/LinuxMakefile/Makefile#L38
Maybe the Makefile(s) need to be generated again?

**Comment by simonvanderveldt** [comment]
Just found this https://forum.juce.com/t/linux-x11-windowing-in-a-vst-3-6-7-plugin-using-juce-components/21767/2
So seems like JUCE doesn't support this on Linux yet :x
