### ISSUE TITLE
GUI refresh bug

### ISSUE THREAD

**Issue by ElenaXX** [paynebc/tunefish#13]
Often the GUI opens with blank pots and numbers and one has to reload the preset or switch to another preset to trigger an update. Very annoying. This at least happens with Reaper (Win7 x64) but chances are it happens with other DAWs/configs aswell. Can you fix this bug please ?

**Comment by alodk** [comment]
I have not seen this problem in Cubase 8.5 Artist on Win 10 X64( TF version 4.1.-4.2).

**Comment by paynebc** [comment]
Never had this issue either in any of the DAWs I tried :(

**Comment by ElenaXX** [comment]
I apologize very much folks... I wanted to post this bug report in Sprike fork actually, but for some reasons I was redirected to Tunefish bug report page without realizing suddently... sorry I am not very familiar with GitHub.
The bug I was referring to affects Sprike, not Tunefish.
*HOWEVER*, I take the occassion to report another bug which affects BOTH Tunefish 4 and Sprike instead... 
After some minutes of operation (15? 20? I couldn't count them) the sound... changes. I discovered the culprit is the Flanger's LFO which apparently stops working. To resume its normal operation I have to either reload the patch/preset or play a bit with the Flanger LFO parameters. One should try with some preset(s) using the flanger, have the synth playing for some time and then check... this hopefully is not DAW related (I am using Reaper x64 with Win 7 64 though). Thanks and I apologize again for my bug report ending up in the wrong place, aargh !!! :)
