### ISSUE TITLE
Flanger LFO stops working after a while

### ISSUE THREAD

**Issue by ElenaXX** [paynebc/tunefish#15]
After some time of operation (15 minutes ? 30 ? I couldn't count them reliably, sorry) the sound gets different. I discovered it's the Flanger LFO (if the preset is using it of course) which stops working and apparently gets stuck. The only way to restore the intended sound is to reload the preset or play with the Flanger/LFO parameters or disable/enable again the Flanger.
Given the nature of the issue, I can suspect the same bug may affect other LFOs aswell (not tested).
I am experiencing this issue with Reaper (x64) but I suspect it is not DAW-related of course. I experienced the very same bug with my previous hardware (core2duo) and with my new one (I7 8700K), therefore I can't suspect it's hardware-related either. Thanks !

**Comment by ElenaXX** [comment]
For your convenience, I am attaching a preset (.fxp) presenting with the above mentioned issue, but I suspect the bug affects any preset using a Flanger with LFO.

**Comment by ElenaXX** [comment]
[TunefishSound.zip](https://github.com/paynebc/tunefish/files/2123480/TunefishSound.zip)

**Comment by paynebc** [comment]
I tried this today with latest build and a simple instrument with only flanger. even after one full hour the sound was still okay and the flanger LFO worked fine. checking the code I could not find anything that looked like it could fail after a certain time (I could be wrong of course)

**Comment by ElenaXX** [comment]
Very strange... maybe this only happens to me because I use Reaper ?! Anyway, I had to stop using tunefish flanger since months because of that problem and I resorted to an external one. Thanks for investigating anyway !

Il 21 Gennaio 2019 16:04:52 CET, Christian Loos <notifications@github.com> ha scritto:
>I tried this today with latest build and a simple instrument with only
>flanger. even after one full hour the sound was still okay and the
>flanger LFO worked fine. checking the code I could not find anything
>that looked like it could fail after a certain time (I could be wrong
>of course)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/paynebc/tunefish/issues/15#issuecomment-456104004

-- Elena
