### ISSUE TITLE
Each note sounds differently

### ISSUE THREAD

**Issue by olegcherr** [paynebc/tunefish#19]
Hi man!
Thanks for your amazing synth Tunefish4!
I love it!

At the moment I'm trying to learn how it works.
I'm wondering why I can't make it sound equally on each note.

I set all the knobs to zeros and disabled all the effects.
Then I created 4 equal notes, and started to monitor the stereo spectrum.
I figured out that each note sounds differently.

I recorded the GIF to illustrate the problem:
![tunefish](https://user-images.githubusercontent.com/3730074/52068673-8ba9e480-2596-11e9-9db5-e96a0b46b63d.gif)

Why? How can I avoid that?

Thank you!

**Comment by paynebc** [comment]
Hi,
glad you like it, thanks :)
Tunefish is designed to be not precise when creating sounds. It is deliberately done this way. You can make that randomness stronger by using the slop parameter but there is no way to switch it off. This is to create a fuller sound with more variation.

**Comment by olegcherr** [comment]
Thanks for the quick reply!
I got your point. But still, what I suppose to do if I made a precise melody and I need to make it sound uniformly and equally? Or if I have a bass line that must be equal during the whole song.
Should I pick another synth? :(

**Comment by olegcherr** [comment]
Moreover, such behavior leads to a much more important problem.
Tunefish sounds differently **every render**!

It might be acceptable for some background sounds of the song. But it definitelly unacceptable for primary sounds (melody, bass, etc).

So, in my opinion you should at least implement the synchronization with the host.
In this case every render will be exactly the same.

**Comment by paynebc** [comment]
Sorry, what you need is currently not possible in Tunefish. Syncing with the host is something I could try to do in the future but don't hold your breath since I have very little time for synth coding these days :(

**Comment by userabc123xyz** [comment]
You can sample a single note and copy it as many times as you need.
