### ISSUE TITLE
High CPU usage after opening the GUI

### ISSUE THREAD

**Issue by rghvdberg** [paynebc/tunefish#3]
Linux Mint 17.3 + kxstudio x64
Ardour 4.7
I compiled a new vst plugin from the latest code
CPU usage is moderate when I start the project with a couple of TF4.1.
If I open the GUI of one the plug-ins the CPU usage jumps up and stays high even after closing the GUI.

Screenshots:
Old TF4.1 | moderate cpu usage
![selectie_038](https://cloud.githubusercontent.com/assets/10710663/16556440/569d08dc-41da-11e6-84a2-17d0c88ae352.png)

New TF4.1 | moderate cpu usage before opening the gui
![selectie_039](https://cloud.githubusercontent.com/assets/10710663/16556442/5bc158d6-41da-11e6-913e-568f071e464f.png)

New TF4.1 | high cpu usage after opening (and closing) the gui of several TF4.1 plugins
![selectie_040](https://cloud.githubusercontent.com/assets/10710663/16556443/5d81c8e0-41da-11e6-81bc-92e76937fd76.png)

**Comment by paynebc** [comment]
can you check with the new config buttons and see how CPU load changes with them?

**Comment by rghvdberg** [comment]
oh my ..
when I open the GUI I get loads of xruns
>Tue Jul  5 13:59:00 2016: ERROR: JackAudioDriver::ProcessGraphAsyncMaster: Process error
>Tue Jul  5 13:59:06 2016: ERROR: JackEngine::XRun: client = ardour was not finished, state = Running
Tue Jul  5 13:59:06 2016: ERROR: JackAudioDriver::ProcessGraphAsyncMaster: Process error
Tue Jul  5 13:59:06 2016: ERROR: JackEngine::XRun: client = ardour was not finished, state = Running

etc
**but .. disabling Animations On seems to help**

**Comment by paynebc** [comment]
Ah I have an idea... will try something

**Comment by paynebc** [comment]
okay, I now reduced the critical section and thus the amount of time the UI locks the synth with the waveform redraw. that might improve the situation

**Comment by rghvdberg** [comment]
it's a lot better but still cpu shoots up when enabling animations
closing gui doesn't help
disabling animations does

no xruns btw
