### ISSUE TITLE
New build ( 490ea9d) crashed Ardour

### ISSUE THREAD

**Issue by rghvdberg** [paynebc/tunefish#4]
build with latest commit  490ea9d 

tried to open the plugin gui in Ardour 4.7
here's a backtrack (dunno if helpful)

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff8d9a0700 (LWP 13272)]
0x00007fffedc49c37 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) thread apply all bt

Thread 90 (Thread 0x7fff98e1e700 (LWP 13279)):
#0  0x00007ffff0c9477d in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007fff8c849662 in juce::WaitableEvent::wait (this=0x7fff84000e80, timeOutMillisecs=300) at ../../JuceLibraryCode/modules/juce_core/native/juce_posix_SharedCode.h:97
#2  0x00007fff8c8b43d8 in juce::Timer::TimerThread::run (this=0x7fff84000d40) at ../../JuceLibraryCode/modules/juce_events/timers/juce_Timer.cpp:75
#3  0x00007fff8c82ec03 in juce::Thread::threadEntryPoint (this=0x7fff84000d40) at ../../JuceLibraryCode/modules/juce_core/threads/juce_Thread.cpp:101
#4  0x00007fff8c82ec6e in juce::juce_threadEntryPoint (userData=0x7fff84000d40) at ../../JuceLibraryCode/modules/juce_core/threads/juce_Thread.cpp:113
#5  0x00007fff8c84b4fc in juce::threadEntryProc (userData=0x7fff84000d40) at ../../JuceLibraryCode/modules/juce_core/native/juce_posix_SharedCode.h:852
#6  0x00007ffff0c90184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00007fffedd0d37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 89 (Thread 0x7fff9961f700 (LWP 13278)):
#0  0x00007fffedd64651 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fffc897d901 in ?? () from /usr/lib/nvidia-352/libGL.so.1
#2  0x00007fffc897dbcb in ?? () from /usr/lib/nvidia-352/libGL.so.1
#3  0x00007fff76c1d97a in ?? () from /usr/lib/nvidia-352/libnvidia-glcore.so.352.63
#4  0x00007fff76c82d8d in ?? () from /usr/lib/nvidia-352/libnvidia-glcore.so.352.63
#5  0x00007fff76c86f87 in ?? () from /usr/lib/nvidia-352/libnvidia-glcore.so.352.63
#6  0x00007fff76c4b916 in ?? () from /usr/lib/nvidia-352/libnvidia-glcore.so.352.63
#7  0x00007fff76c4bc45 in ?? () from /usr/lib/nvidia-352/libnvidia-glcore.so.352.63
#8  0x00007fff76c3b282 in ?? () from /usr/lib/nvidia-352/libnvidia-glcore.so.352.63
#9  0x00007fff76c188dc in ?? () from /usr/lib/nvidia-352/libnvidia-glcore.so.352.63
#10 0x00007fffc897c090 in ?? () from /usr/lib/nvidia-352/libGL.so.1
#11 0x00007fffc897c249 in ?? () from /usr/lib/nvidia-352/libGL.so.1
#12 0x00007fffc89ae0be in ?? () from /usr/lib/nvidia-352/libGL.so.1
#13 0x00007fff8caeaf46 in juce::OpenGLContext::NativeContext::makeActive (this=0x7fff8407fef0) at ../../JuceLibraryCode/modules/juce_opengl/native/juce_OpenGL_linux.h:156
#14 0x00007fff8cae3867 in juce::OpenGLContext::makeActive (this=0x7fff84001a30) at ../../JuceLibraryCode/modules/juce_opengl/opengl/juce_OpenGLContext.cpp:778
#15 0x00007fff8caeae84 in juce::OpenGLContext::NativeContext::initialiseOnRenderThread (this=0x7fff8407fef0, c=...) at ../../JuceLibraryCode/modules/juce_opengl/native/juce_OpenGL_linux.h:141
#16 0x00007fff8caec776 in juce::OpenGLContext::CachedImage::initialiseOnThread (this=0x7fff8407fc90) at ../../JuceLibraryCode/modules/juce_opengl/opengl/juce_OpenGLContext.cpp:449
#17 0x00007fff8caec5f9 in juce::OpenGLContext::CachedImage::runJob (this=0x7fff8407fc90) at ../../JuceLibraryCode/modules/juce_opengl/opengl/juce_OpenGLContext.cpp:411
#18 0x00007fff8c83020b in juce::ThreadPool::runNextJob (this=0x7fff84080ea0, thread=...) at ../../JuceLibraryCode/modules/juce_core/threads/juce_ThreadPool.cpp:341
#19 0x00007fff8c86b262 in juce::ThreadPool::ThreadPoolThread::run (this=0x7fff84082ba0) at ../../JuceLibraryCode/modules/juce_core/threads/juce_ThreadPool.cpp:40
#20 0x00007fff8c82ec03 in juce::Thread::threadEntryPoint (this=0x7fff84082ba0) at ../../JuceLibraryCode/modules/juce_core/threads/juce_Thread.cpp:101
#21 0x00007fff8c82ec6e in juce::juce_threadEntryPoint (userData=0x7fff84082ba0) at ../../JuceLibraryCode/modules/juce_core/threads/juce_Thread.cpp:113
#22 0x00007fff8c84b4fc in juce::threadEntryProc (userData=0x7fff84082ba0) at ../../JuceLibraryCode/modules/juce_core/native/juce_posix_SharedCode.h:852
#23 0x00007ffff0c90184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#24 0x00007fffedd0d37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 88 (Thread 0x7fff8d9a0700 (LWP 13272)):
#0  0x00007fffedc49c37 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fffedc4d028 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007fffedc42bf6 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007fffedc42ca2 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff048d79c in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#5  0x00007ffff048e5c3 in _XReply () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#6  0x00007ffff0475346 in XGetWindowProperty () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#7  0x00007fff8ca610c9 in juce::GetXProperty::GetXProperty (this=0x7fff8d99fa90, window=58720260, atom=387, offset=0, length=64, shouldDelete=false, requestedType=387)
    at ../../JuceLibraryCode/modules/juce_gui_basics/native/juce_linux_Windowing.cpp:128
#8  0x00007fff8ca6550f in juce::LinuxComponentPeer::isMinimised (this=0x7fff84065df0) at ../../JuceLibraryCode/modules/juce_gui_basics/native/juce_linux_Windowing.cpp:1722
#9  0x00007fff8c994241 in juce::Component::isShowing (this=0x7fff8407cf80) at ../../JuceLibraryCode/modules/juce_gui_basics/components/juce_Component.cpp:579
#10 0x00007fff8c994211 in juce::Component::isShowing (this=0x7fff84001920) at ../../JuceLibraryCode/modules/juce_gui_basics/components/juce_Component.cpp:576
#11 0x00007fff8c6fbee8 in Tunefish4AudioProcessorEditor::refreshUiFromSynth (this=0x7fff84001920) at ../../Source/PluginEditor.cpp:596
#12 0x00007fff8c6fbec4 in Tunefish4AudioProcessorEditor::timerCallback (this=0x7fff84001920) at ../../Source/PluginEditor.cpp:591
#13 0x00007fff8c8b450d in juce::Timer::TimerThread::callTimers (this=0x7fff84000d40) at ../../JuceLibraryCode/modules/juce_events/timers/juce_Timer.cpp:109
#14 0x00007fff8c8b4787 in juce::Timer::TimerThread::CallTimersMessage::messageCallback (this=0x7fffb4001100) at ../../JuceLibraryCode/modules/juce_events/timers/juce_Timer.cpp:174
#15 0x00007fff8c8b61e3 in juce::InternalMessageQueue::dispatchNextInternalMessage (this=0x7fff7c000a00) at ../../JuceLibraryCode/modules/juce_events/native/juce_linux_Messaging.cpp:202
#16 0x00007fff8c8b5b6d in juce::InternalMessageQueue::dispatchNextEvent (this=0x7fff7c000a00) at ../../JuceLibraryCode/modules/juce_events/native/juce_linux_Messaging.cpp:93
#17 0x00007fff8c8b3569 in juce::MessageManager::dispatchNextMessageOnSystemQueue (returnIfNoPendingMessages=true) at ../../JuceLibraryCode/modules/juce_events/native/juce_linux_Messaging.cpp:390
#18 0x00007fff8c8af687 in juce::MessageManager::runDispatchLoopUntil (this=0x7fff7c002890, millisecondsToRunFor=250) at ../../JuceLibraryCode/modules/juce_events/messages/juce_MessageManager.cpp:94
#19 0x00007fff8cb00bc7 in SharedMessageThread::run (this=0x2efcc60) at ../../JuceLibraryCode/modules/juce_audio_plugin_client/VST/juce_VST_Wrapper.cpp:230
#20 0x00007fff8c82ec03 in juce::Thread::threadEntryPoint (this=0x2efcc60) at ../../JuceLibraryCode/modules/juce_core/threads/juce_Thread.cpp:101
#21 0x00007fff8c82ec6e in juce::juce_threadEntryPoint (userData=0x2efcc60) at ../../JuceLibraryCode/modules/juce_core/threads/juce_Thread.cpp:113
#22 0x00007fff8c84b4fc in juce::threadEntryProc (userData=0x2efcc60) at ../../JuceLibraryCode/modules/juce_core/native/juce_posix_SharedCode.h:852
#23 0x00007ffff0c90184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#24 0x00007fffedd0d37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 38 (Thread 0x7fff9bfff700 (LWP 13093)):
#0  0x00007ffff0c97b9d in nanosleep () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffff50b2298 in g_usleep () from /opt/ardour4/lib/libglib-2.0.so.0
#2  0x00007ffff6d74fff in ARDOUR::AutomationWatch::thread() () from /opt/ardour4/lib/libardour.so.3
#3  0x00007ffff560fb72 in ?? () from /opt/ardour4/lib/libglibmm-2.4.so.1
#4  0x00007ffff50b07f5 in ?? () from /opt/ardour4/lib/libglib-2.0.so.0
#5  0x00007ffff0c90184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007fffedd0d37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 37 (Thread 0x7fffca356700 (LWP 13092)):
#0  0x00007ffff0c94404 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffff701b5a3 in ARDOUR::Session::emit_thread_run() () from /opt/ardour4/lib/libardour.so.3
#2  0x00007ffff701b5c9 in ARDOUR::Session::emit_thread(void*) () from /opt/ardour4/lib/libardour.so.3
#3  0x00007ffff0c90184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#4  0x00007fffedd0d37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 36 (Thread 0x7fffb908c700 (LWP 13091)):
#0  0x00007fffedd04c53 in select () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fffc8cc930f in ?? () from /usr/lib/lv2/TAL-Reverb-2.lv2/TAL-Reverb-2.so
#2  0x00007fffc8cc953f in ?? () from /usr/lib/lv2/TAL-Reverb-2.lv2/TAL-Reverb-2.so
#3  0x00007fffc8c8f267 in ?? () from /usr/lib/lv2/TAL-Reverb-2.lv2/TAL-Reverb-2.so
#4  0x00007fffc8cbf614 in ?? () from /usr/lib/lv2/TAL-Reverb-2.lv2/TAL-Reverb-2.so
#5  0x00007fffc8cbf869 in ?? () from /usr/lib/lv2/TAL-Reverb-2.lv2/TAL-Reverb-2.so
#6  0x00007ffff0c90184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00007fffedd0d37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 35 (Thread 0x7fffcab57700 (LWP 13090)):
#0  0x00007fffedcfffdd in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff5085aa5 in ?? () from /opt/ardour4/lib/libglib-2.0.so.0
#2  0x00007ffff5085bb5 in g_main_loop_run () from /opt/ardour4/lib/libglib-2.0.so.0
#3  0x00007ffff61b465c in BaseUI::main_thread() () from /opt/ardour4/lib/libpbd.so.4
#4  0x00007ffff560fb72 in ?? () from /opt/ardour4/lib/libglibmm-2.4.so.1
#5  0x00007ffff50b07f5 in ?? () from /opt/ardour4/lib/libglib-2.0.so.0
#6  0x00007ffff0c90184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00007fffedd0d37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 34 (Thread 0x7fffc98cf800 (LWP 13089)):
#0  0x00007fffedcfffdd in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff61c0b84 in CrossThreadChannel::poll_for_request() () from /opt/ardour4/lib/libpbd.so.4
#2  0x00007ffff61c0bea in CrossThreadChannel::receive(char&, bool) () from /opt/ardour4/lib/libpbd.so.4
#3  0x00007ffff6d826e1 in ARDOUR::Butler::thread_work() () from /opt/ardour4/lib/libardour.so.3
#4  0x00007ffff6d82daf in ARDOUR::Butler::_thread_work(void*) () from /opt/ardour4/lib/libardour.so.3
#5  0x00007ffff61dbd40 in ?? () from /opt/ardour4/lib/libpbd.so.4
#6  0x00007ffff0c90184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00007fffedd0d37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 33 (Thread 0x7fffc9951700 (LWP 13088)):
#0  0x00007ffff0c96670 in sem_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffff6e2b0f5 in ARDOUR::Graph::restart_cycle() () from /opt/ardour4/lib/libardour.so.3
#2  0x00007ffff6e2ad91 in ARDOUR::Graph::run_one() () from /opt/ardour4/lib/libardour.so.3
#3  0x00007ffff6e2ae08 in ARDOUR::Graph::helper_thread() () from /opt/ardour4/lib/libardour.so.3
#4  0x00000000008703d3 in boost::function0<void>::operator()() const ()
#5  0x00007fffd973f8c9 in ARDOUR::JACKAudioBackend::_start_process_thread(void*) () from /opt/ardour4/lib/backends/libjack_audiobackend.so
#6  0x00007ffff0c90184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00007fffedd0d37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 32 (Thread 0x7fffc99d2700 (LWP 13087)):
#0  0x00007ffff0c96670 in sem_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffff6e2ad3f in ARDOUR::Graph::run_one() () from /opt/ardour4/lib/libardour.so.3
#2  0x00007ffff6e2ae08 in ARDOUR::Graph::helper_thread() () from /opt/ardour4/lib/libardour.so.3
#3  0x00000000008703d3 in boost::function0<void>::operator()() const ()
#4  0x00007fffd973f8c9 in ARDOUR::JACKAudioBackend::_start_process_thread(void*) () from /opt/ardour4/lib/backends/libjack_audiobackend.so
#5  0x00007ffff0c90184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007fffedd0d37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 31 (Thread 0x7fffc9a53700 (LWP 13086)):
#0  0x00007ffff0c96670 in sem_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffff6e2ad3f in ARDOUR::Graph::run_one() () from /opt/ardour4/lib/libardour.so.3
#2  0x00007ffff6e2b061 in ARDOUR::Graph::main_thread() () from /opt/ardour4/lib/libardour.so.3
#3  0x00000000008703d3 in boost::function0<void>::operator()() const ()
#4  0x00007fffd973f8c9 in ARDOUR::JACKAudioBackend::_start_process_thread(void*) () from /opt/ardour4/lib/backends/libjack_audiobackend.so
#5  0x00007ffff0c90184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007fffedd0d37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 29 (Thread 0x7fffc9ad4700 (LWP 13082)):
#0  0x00007fffedd07709 in syscall () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fffd9505ac8 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#2  0x00007fffd94e8ee5 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#3  0x00007fffd94e7837 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#4  0x00007fffd973f0e2 in ARDOUR::JACKAudioBackend::process_thread() () from /opt/ardour4/lib/backends/libjack_audiobackend.so
#5  0x00007fffd94e77aa in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#6  0x00007fffd9503a70 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#7  0x00007ffff0c90184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00007fffedd0d37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 28 (Thread 0x7fffc9b55700 (LWP 13081)):
#0  0x00007ffff0c973ad in read () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007fffd9504ec4 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#2  0x00007fffd95083ac in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#3  0x00007fffd9503a70 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#4  0x00007ffff0c90184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007fffedd0d37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 27 (Thread 0x7fffd80dd700 (LWP 13080)):
#0  0x00007ffff0c94404 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007fffd95046bc in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#2  0x00007fffd94fbbb8 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#3  0x00007fffd9503a70 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#4  0x00007ffff0c90184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007fffedd0d37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 13 (Thread 0x7fffcb76e700 (LWP 13034)):
#0  0x00007fffedcfffdd in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff5085aa5 in ?? () from /opt/ardour4/lib/libglib-2.0.so.0
#2  0x00007ffff5085cc7 in g_main_context_iteration () from /opt/ardour4/lib/libglib-2.0.so.0
#3  0x00007ffff5085d19 in ?? () from /opt/ardour4/lib/libglib-2.0.so.0
#4  0x00007ffff50b07f5 in ?? () from /opt/ardour4/lib/libglib-2.0.so.0
#5  0x00007ffff0c90184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007fffedd0d37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 7 (Thread 0x7fffda893700 (LWP 13028)):
#0  0x00007ffff0c94404 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffff50d1524 in g_cond_wait () from /opt/ardour4/lib/libglib-2.0.so.0
#2  0x00007ffff6d349bb in ARDOUR::AudioEngine::do_devicelist_update() () from /opt/ardour4/lib/libardour.so.3
#3  0x00007ffff560fb72 in ?? () from /opt/ardour4/lib/libglibmm-2.4.so.1
#4  0x00007ffff50b07f5 in ?? () from /opt/ardour4/lib/libglib-2.0.so.0
#5  0x00007ffff0c90184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007fffedd0d37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 6 (Thread 0x7fffdb094700 (LWP 13027)):
#0  0x00007ffff0c94404 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffff50d1524 in g_cond_wait () from /opt/ardour4/lib/libglib-2.0.so.0
#2  0x00007ffff6d34cad in ARDOUR::AudioEngine::do_reset_backend() () from /opt/ardour4/lib/libardour.so.3
#3  0x00007ffff560fb72 in ?? () from /opt/ardour4/lib/libglibmm-2.4.so.1
#4  0x00007ffff50b07f5 in ?? () from /opt/ardour4/lib/libglib-2.0.so.0
#5  0x00007ffff0c90184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007fffedd0d37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 5 (Thread 0x7fffe8bc0700 (LWP 13026)):
#0  0x00007ffff0c94404 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffff50d1524 in g_cond_wait () from /opt/ardour4/lib/libglib-2.0.so.0
#2  0x00007ffff6cf8adb in ARDOUR::Analyser::work() () from /opt/ardour4/lib/libardour.so.3
#3  0x00007ffff560fb72 in ?? () from /opt/ardour4/lib/libglibmm-2.4.so.1
#4  0x00007ffff50b07f5 in ?? () from /opt/ardour4/lib/libglib-2.0.so.0
#5  0x00007ffff0c90184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007fffedd0d37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 4 (Thread 0x7fffe93c1700 (LWP 13025)):
#0  0x00007ffff0c94404 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffff50d1524 in g_cond_wait () from /opt/ardour4/lib/libglib-2.0.so.0
#2  0x00007ffff706976b in ?? () from /opt/ardour4/lib/libardour.so.3
#3  0x00007ffff560fb72 in ?? () from /opt/ardour4/lib/libglibmm-2.4.so.1
#4  0x00007ffff50b07f5 in ?? () from /opt/ardour4/lib/libglib-2.0.so.0
#5  0x00007ffff0c90184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007fffedd0d37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 3 (Thread 0x7fffe9bc2700 (LWP 13024)):
#0  0x00007ffff0c94404 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffff50d1524 in g_cond_wait () from /opt/ardour4/lib/libglib-2.0.so.0
#2  0x00007ffff706976b in ?? () from /opt/ardour4/lib/libardour.so.3
#3  0x00007ffff560fb72 in ?? () from /opt/ardour4/lib/libglibmm-2.4.so.1
#4  0x00007ffff50b07f5 in ?? () from /opt/ardour4/lib/libglib-2.0.so.0
#5  0x00007ffff0c90184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007fffedd0d37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7fffea3c3700 (LWP 13023)):
#0  0x00007fffedcfffdd in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fffec455b72 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007fffec4573ff in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007fffec457512 in xcb_wait_for_reply () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#4  0x00007ffff048e48f in _XReply () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#5  0x00007ffff0475346 in XGetWindowProperty () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#6  0x0000000000c20e34 in ?? ()
#7  0x0000000000c20ff5 in ?? ()
#8  0x00007ffff0c90184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#9  0x00007fffedd0d37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7ffff7fa4900 (LWP 13019)):
#0  0x00007ffff7de3fa4 in ?? () from /lib64/ld-linux-x86-64.so.2
#1  0x00007ffff7de4961 in ?? () from /lib64/ld-linux-x86-64.so.2
#2  0x00007ffff7de9527 in ?? () from /lib64/ld-linux-x86-64.so.2
#3  0x00007ffff7df04d5 in ?? () from /lib64/ld-linux-x86-64.so.2
#4  0x00007ffff413ec9d in ?? () from /opt/ardour4/lib/libgdk-x11-2.0.so.0
#5  0x00007ffff4110d3a in gdk_window_hide () from /opt/ardour4/lib/libgdk-x11-2.0.so.0
#6  0x00007ffff4578df9 in ?? () from /opt/ardour4/lib/libgtk-x11-2.0.so.0
#7  0x0000000000c22819 in ?? ()
#8  0x0000000000c2202a in ?? ()
#9  0x000000000097fcd0 in ?? ()
#10 0x0000000000980893 in ?? ()
#11 0x00000000009c9755 in ?? ()
#12 0x00000000009c9e40 in ?? ()
#13 0x0000000000bcf44e in ?? ()
#14 0x00000000009c4967 in ?? ()
#15 0x00000000009c4d94 in ?? ()
#16 0x00000000009d273f in ?? ()
#17 0x00007ffff25b6682 in ?? () from /opt/ardour4/lib/libgtkmm-2.4.so.1
#18 0x00007ffff44f2f38 in ?? () from /opt/ardour4/lib/libgtk-x11-2.0.so.0
#19 0x00007ffff53881e2 in g_closure_invoke () from /opt/ardour4/lib/libgobject-2.0.so.0
#20 0x00007ffff539f03d in ?? () from /opt/ardour4/lib/libgobject-2.0.so.0
#21 0x00007ffff539ff98 in g_signal_emit_valist () from /opt/ardour4/lib/libgobject-2.0.so.0
#22 0x00007ffff53a07e3 in g_signal_emit () from /opt/ardour4/lib/libgobject-2.0.so.0
#23 0x00007ffff4649d8f in ?? () from /opt/ardour4/lib/libgtk-x11-2.0.so.0
#24 0x00007ffff44eb0d3 in gtk_propagate_event () from /opt/ardour4/lib/libgtk-x11-2.0.so.0
#25 0x00007ffff44ecc4b in gtk_main_do_event () from /opt/ardour4/lib/libgtk-x11-2.0.so.0
#26 0x00007ffff4127f7c in ?? () from /opt/ardour4/lib/libgdk-x11-2.0.so.0
#27 0x00007ffff5083dae in g_main_context_dispatch () from /opt/ardour4/lib/libglib-2.0.so.0
#28 0x00007ffff5085b08 in ?? () from /opt/ardour4/lib/libglib-2.0.so.0
#29 0x00007ffff5085bb5 in g_main_loop_run () from /opt/ardour4/lib/libglib-2.0.so.0
#30 0x00007ffff44ec657 in gtk_main () from /opt/ardour4/lib/libgtk-x11-2.0.so.0
#31 0x00007ffff76ca2c4 in Gtkmm2ext::UI::run(Receiver&) () from /opt/ardour4/lib/libgtkmm2ext.so.0
#32 0x000000000081d5ea in ?? ()
#33 0x00007fffedc34f45 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#34 0x000000000048eec9 in ?? ()
#35 0x00007fffffffd288 in ?? ()
#36 0x000000000000001c in ?? ()
#37 0x0000000000000001 in ?? ()
#38 0x00007fffffffd5e7 in ?? ()
#39 0x0000000000000000 in ?? ()
(gdb)

**Comment by paynebc** [comment]
probably the opengl change. I reverted it, please check again

**Comment by rghvdberg** [comment]
great all working good!
