### ISSUE TITLE
Pitch wheel notes are way off

### ISSUE THREAD

**Issue by kzantow** [paynebc/tunefish#5]
Set pitch bend ranges +/-12 Play C4 bend up 100% (should be C5). Play C6 bend down 100% (should be C5), but instead totally different notes. Seems the scaling goes up a lot more the higher the base pitch, perhaps.
Tunefish 4.0.1, OSX 10.11, Bitwig 1.3.11

**Comment by paynebc** [comment]
Fixed this finally :)
