### ISSUE TITLE
Pitch changes when setting pitchbend, without any pitchbend applied.

### ISSUE THREAD

**Issue by rghvdberg** [paynebc/tunefish#6]
I think this is related to #5 

Pitch up set to 1:
![tunefish4 gui _042](https://cloud.githubusercontent.com/assets/10710663/16767455/d7b4ca3e-483f-11e6-8c37-7b37edf59a24.png)
Pitch up set to 12, no pitchbend applied :
![tunefish4 gui _043](https://cloud.githubusercontent.com/assets/10710663/16767458/d95f8a04-483f-11e6-8f7e-46e79619d6b0.png)

**Comment by paynebc** [comment]
Yes it was related and should be fixed in next release 4.2.0
